<template>
    <div class="wrapperSocial flexColumn">
        <!-- <div class="render flicker-in-2">
            <div class="page">
               

            </div>
        </div> -->

        <h1 class="title">Caso você tenha a preferência, também poderá acessar as minhas redes sociais:</h1>
        <div class="flexRow align-items-center itemWrapper">
            <h1 @mouseenter="mouseEnter"> <a href="http://" target="_blank" rel="noopener noreferrer"> LinkedIn</a> </h1>

        </div>
        <div class="flexRow align-items-center itemWrapper">
            <h1><a href="http://" target="_blank" rel="noopener noreferrer">GitHub</a></h1>

        </div>
        <div class="flexRow align-items-center itemWrapper">
            <h1><a href="http://" target="_blank" rel="noopener noreferrer">WhatsApp</a></h1>

        </div>

    </div>
</template>
<script lang="ts">
import { Vue, Options } from 'vue-class-component';
Options({

})
export default class mediaSocial extends Vue {
    mouseEnter() {
        console.log('a');
    }

    mounted(){
        new Promise<void>((sucess)=>{
            const http = new XMLHttpRequest();
            http.onreadystatechange = function(){
                if(this.readyState == 4 && this.status == 200){
                    sucess = http.response;
                    sucess();
                }
            }
            http.open('GET', 'https://www.youtube.com/');
            http.send()
        }).then((sucess)=>{
            console.log(sucess);
        })
    }
}
</script>
<style scoped>
div.render div.page {
    background-color: var(--corPreto);
    border-radius: 10px;
    box-shadow: 0 0 15px var(--corPreto), 0 0 10px var(--corPreto), 0 0 5px var(--corPreto);
    width: 100%;
    min-width: 400px;
    height: 100%;
}

div.render {
    background-color: rgba(255, 255, 255, 0.603);
    border-radius: 30px;
    padding: 1%;
    width: 50%;
    height: 80%;
    position: fixed;
    z-index: 99;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

div.wrapperSocial {
    padding: 2%;
    background-color: var(--corBranco);
    height: 50%;
}

h1.title {
    font-size: 1.2vw;
    text-align: center;
    background-color: white;
}

div.wrapperSocial div.itemWrapper {
    background-color: red;
    height: 3.5vw;
    height:50%;
}

div.wrapperSocial div.itemWrapper h1 {
    /* padding: 2%; */
    font-size: 1.2vw;
    width:100%;
    background-color: green;
    height: 100%;
   
}

h1 > a{
    display:flex;
    align-items: center;
    text-decoration: none;
    height: calc(100% - 4%);
    padding: 0 2%;
    width:100%;
    background-color: red;

}
.flicker-in-2 {
    -webkit-animation: flicker-in-2 2s linear both;
    animation: flicker-in-2 2s linear both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-5-7 10:5:2
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * @animation flicker-in-2
 * ----------------------------------------
 */
@-webkit-keyframes flicker-in-2 {
    0% {
        opacity: 0;
    }

    10% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    10.1% {
        opacity: 1;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    10.2% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    20% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    20.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.25);
    }

    20.6% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    30% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    30.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
    }

    30.5% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
    }

    30.6% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    45% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    45.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
    }

    50% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
    }

    55% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
    }

    55.1% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    57% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    57.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3);
    }

    60% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3);
    }

    60.1% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    65% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    65.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3), 0 0 100px rgba(255, 255, 255, 0.1);
    }

    75% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3), 0 0 100px rgba(255, 255, 255, 0.1);
    }

    75.1% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    77% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    77.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.4), 0 0 110px rgba(255, 255, 255, 0.2), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.4), 0 0 110px rgba(255, 255, 255, 0.2), 0 0 100px rgba(255, 255, 255, 0.1);
    }

    85% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.4), 0 0 110px rgba(255, 255, 255, 0.2), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.4), 0 0 110px rgba(255, 255, 255, 0.2), 0 0 100px rgba(255, 255, 255, 0.1);
    }

    85.1% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    86% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    86.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.45), 0 0 110px rgba(255, 255, 255, 0.25), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.45), 0 0 110px rgba(255, 255, 255, 0.25), 0 0 100px rgba(255, 255, 255, 0.1);
    }

    100% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.45), 0 0 110px rgba(255, 255, 255, 0.25), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.45), 0 0 110px rgba(255, 255, 255, 0.25), 0 0 100px rgba(255, 255, 255, 0.1);
    }
}

@keyframes flicker-in-2 {
    0% {
        opacity: 0;
    }

    10% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    10.1% {
        opacity: 1;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    10.2% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    20% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    20.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.25);
    }

    20.6% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    30% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    30.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
    }

    30.5% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
    }

    30.6% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    45% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    45.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
    }

    50% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
    }

    55% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.45), 0 0 60px rgba(255, 255, 255, 0.25);
    }

    55.1% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    57% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    57.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3);
    }

    60% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3);
    }

    60.1% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    65% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    65.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3), 0 0 100px rgba(255, 255, 255, 0.1);
    }

    75% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.55), 0 0 60px rgba(255, 255, 255, 0.3), 0 0 100px rgba(255, 255, 255, 0.1);
    }

    75.1% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    77% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    77.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.4), 0 0 110px rgba(255, 255, 255, 0.2), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.4), 0 0 110px rgba(255, 255, 255, 0.2), 0 0 100px rgba(255, 255, 255, 0.1);
    }

    85% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.4), 0 0 110px rgba(255, 255, 255, 0.2), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.4), 0 0 110px rgba(255, 255, 255, 0.2), 0 0 100px rgba(255, 255, 255, 0.1);
    }

    85.1% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    86% {
        opacity: 0;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    86.1% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.45), 0 0 110px rgba(255, 255, 255, 0.25), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.45), 0 0 110px rgba(255, 255, 255, 0.25), 0 0 100px rgba(255, 255, 255, 0.1);
    }

    100% {
        opacity: 1;
        -webkit-box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.45), 0 0 110px rgba(255, 255, 255, 0.25), 0 0 100px rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.6), 0 0 60px rgba(255, 255, 255, 0.45), 0 0 110px rgba(255, 255, 255, 0.25), 0 0 100px rgba(255, 255, 255, 0.1);
    }
}
</style>